services:
  nginx:
    image: nginx:stable
    ports:
      - "8085:80"
    volumes:
      - .:/app:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    volumes:
      - .:/app:cached
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: "pgsql://symfony:symfony@db:5432/axium_db"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: axium_db
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
