services:
  php:
    build: .
    volumes:
      - .:/app:cached
    ports:
      - "8085:8085"  # ← Puerto externo e interno
    command: php -S 0.0.0.0:8085 -t public
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: "pgsql://symfony:symfony@db:5432/axium_db"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: axium_db
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  pgdata:
