services:
  php:
    build:
      context: .
    container_name: axium_test-php-1
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: "pgsql://symfony:symfony@db:5432/axium_db"

  db:
    image: postgres:15
    container_name: axium_test-db-1
    environment:
      POSTGRES_DB: axium_db
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
